BLD: link to libatomic if necessary
Add a test (using the check code from Mesa) whether 64-bit atomic
builtins work correctly without additional libraries, and link to
libatomic if they do not. This fixes creating _highs_wrapper extension
that fails to load due to missing symbols, e.g.:

    ImportError: /home/fhnw/.pyenv/versions/flask3.11.1/lib/python3.11/site-packages/scipy/optimize/_highs/_highs_wrapper.cpython-311-arm-linux-gnueabihf.so: undefined symbol: __atomic_compare_exchange_8

Closes #17670