MAINT: interpolate: appease the linter
In fact, this *does* smoke out a duplicated test name via
test_fitpack2.py:1149:5: F811 redefinition of unused 'test_invalid_input' from line 1059