DOC: Move note about system identification
Move to Notes section instead of after plotting, to work around
https://github.com/matplotlib/matplotlib/issues/19111

Causing the doc build errors:

WARNING: Exception occurred in plotting scipy-fft-czt-1
 from /home/circleci/repo/doc/source/generated/scipy.fft.czt.rst:
Traceback (most recent call last):
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/matplotlib/sphinxext/plot_directive.py", line 472, in run_code
    exec(code, ns)
  File "<string>", line 2
    A similar process can be used for system identification purposes,
            ^
SyntaxError: invalid syntax