Fix for error while using PIL with
python3.6/site-packages/scipy/misc/pilutil.py", line 97, in bytescale
    cscale = cmax - cmin
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.


lib/python3.6/site-packages/scipy/misc/pilutil.py", line 105, in bytescale
    bytedata = (data - cmin) * scale + low