DOC: fix evaluate_all_bspl example.
1) the first argument of `evaluate_all_bspline` need to be an array and
   not a list, or it crashes:

     File "_bspl.pyx", line 163, in scipy.interpolate._bspl.evaluate_all_bspl
     File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
     File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
     TypeError: a bytes-like object is required, not 'list'

So fix it.

2) The initial values were I believe wrong (`2` was present twice)

3) Matplotlib default are sane-er now, so use default color, and reduce
   lw a bit.

4) Also add label for basis element

[ci skip]
[skip azp]
[skip circle]