MAINT: integrate: Better error messages for odeint
When y0 or t has more than one dimension, a ValueError is raised.
This has not been changed, but instead of this cryptic error message:
    ValueError: object too deep for desired array
the error is now
    ValueError: Initial condition y0 must be one-dimensional.
or
    ValueError: Output times t must be one-dimensional.