BF: return NULL from failed Py3 module check
Return NULL rather than bare return from Python 3 module check.

This causes clang to error during build of form:

  scipy/sparse/linalg/dsolve/_superlumodule.c:334:2: error: non-void
  function 'PyInit__superlu' should return a value [-Wreturn-type]

            return;

See:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/205184825/log.txt