MAINT: optimize: fix usage of `nextafter(..., where=)` without `out=`.
This raises a warning now (after numpy#29813) because it returns uninitialized
memory. The usage seems correct, so I left the code as is, although the
performance difference of using `where=` over `np.where` is probably
negligible.

Fixes CI failures in jobs using numpy nightlies that look like:
```
 FAILED scipy/optimize/tests/test_minimize_constrained.py::test_gh11649 - UserWarning: 'where' used without 'out', expect unitialized memory in output. If this is intentional, use out=None.
```