Add Chirp Z-transform, zoom FFT (#4607)
* Add chirp z-transform, zoom FFT, scaled FFT

Written by Paul Kienzle and Nadav Horesh, published to public domain in
mailing list post "[SciPy-user] Chirp Z transform"
http://mail.scipy.org/pipermail/scipy-user/2009-March/020331.html

* DOC: Fix typos, argument ordering and "optional"

* API: zoomfft uses tuple for frequency range

Change API so that frequency range is specified as a tuple instead of 2
arguments, like `butter` and other filter design functions.  Change
examples and tests to match.

Also fix a complex cast in the demo

* Add standard imports, remove unused import

Add czt imports to scipy.fftpack __init__.py

* DOC: Misc docstring fixes, PEP8 spacing

Credit Kienzle and Horesh in THANKS.txt

* TST: Cleanup CZT tests

Add specific example signals from the demo, add basic CZT test,
reorganize into tests of each feature, use numpy's assert_, add seed
for deterministic randomness, remove tests from demos
Add interpolation of spectrum and large prime sizes.

* ENH: Pad to next regular length

FFTPACK is optimized for 5-smooth composite lengths, not just powers of
2, so this should be faster.

Since this is specific to FFTPACK, move _next_regular to fftpack.helper.

* API: Move frequency scale factor to own argument

instead of having different behavior for w=1 vs w=1+0j

(name could be changed before merging)

* BUG: prevent overflow of k**2

(must be int__ type, not uint__)

* MAINT: Handle 0-size and 0-ndim input same as fft

and add a test for 1-length input

* DOC: Various docstring improvements

* ENH: Add czt_points func and method

Convenience function for returning the points on the Z plane at which
the CZT samples it, somewhat analogous to `fftfreqs`.  Also available as
.points() in a CZT instance.

* DOC: misc docstring fixes

* BUG: integer `a` was causing errors

* TST: Add czt_points func and method

Also add tests for czt_points

* ENH: Improve accuracy for FFT-like transforms

Any error in `w` is accumulated and causes the sampling spiral to drift
away from the unit circle, resulting in increasing error at the end of
the transform output. When specified using factor (or left blank), we
can do better by generating the points along the unit circle directly,
improving accuracy for the common FFT-like transforms.

Also tighten tests for improved accuracy

* TST: Add tests for math and conflicting args

Test czt with known outputs, make sure it errors if w and factor are
both specified

* DOC: Add CZT functions and classes to listing

* MAINT: combine input sizes validation code

also use new-style classes, same as other SciPy classes

* TST: add tests for invalid sizes, etc.

Also seterr so tests fail if overflows occur inside CZT.

* DOC: Rename 'factor' to 'scale'

This behaves the same way as the scale parameter in ScaledFFT

* ENH: use 'scale' to compute ZoomFFT and ScaledFFT

This method is more accurate for transforms that calculate along
circles, which ZoomFFT and ScaledFFT both do.

* DOC: Move docstrings from __init__ to class

Following NumPy HOWTO:
"Class docstring

Use the same sections as outlined above (all except Returns are
applicable). The constructor (__init__) should also be documented here,
the Parameters section of the docstring details the constructors
parameters."

* DOC: Various docstring cleanups

Add more examples, move notes to Notes section, clarify starting point
is in complex plane, add references, add links to other functions, etc.

* MAINT: Remove demos and tests from module

* DOC: Add more examples, clarify that a is complex

* DOC: Fix problems with doctests

Now they all pass doctest.testfile('czt.py') except for
"Expected nothing, Got: something" errors.

* MAINT: Remove unnecessary arange call

* Remove ScaledFFT to simplify pull request

This is specifically for convolution, hasn't been as thoroughly
discussed, and can always be added in a different PR.

* MAINT: Rename _next_regular to _next_opt_len

"Regular number" is specific to FFTPACK.  Other libraries support other
radices, so gave the function a more generic name, so that pyfftw etc.
can monkey-patch it along with the fft.

* Remove mutually exclusive `scale` parameter

This can be handled by a different class/function in the future if
desired.

Instead of calling CZT.__init__() from `ZoomFFT`, the init code is now
duplicated.

* DOC: Clarify Bluestein algorithm vs CZT

The CZT and DFT are transforms, while Cooley-Tukey algorithm and
Bluestein algorithm are implementations.  The speed-up for prime-length
DFTs arises from Bluestein's algorithm, not CZT.  The CZT could also use
a "direct" implementation, which would not provide any speedup.

* Remove Python 2 code

SciPy has dropped support for it

Also PEP8 whitespace changes

* Update _next_opt_len -> next_fast_len

This was changed into a public function since the PR

* Move CZT from fftpack to fft

fftpack has been deprecated since this PR

* TST: Call test functions instead of yielding them

"yield tests were removed in pytest 4.0 - test_1D will be ignored"

* Improve refguide, correct CZT imports

ScaledFFT and scaledfft were removed from the module, and czt_points
added but refguide was not updated.

Fixes:

ERROR: objects in scipy.fft.__all__ but not in refguide::
    CZT
    ZoomFFT
    czt
    czt_points
    ...
    zoomfft

* DOC: Remove CZT examples

FFT vs CZT speed example is no longer true, since both fft and czt use
Bluestein's algorithm now.

Scaled example is no longer valid, because scale parameter was removed

* DOC: Add import commands to doctests

"NameError: name 'fft' is not defined", etc.

* DOC: Remove inaccurate FFT comparisons

* Make fs= parameter lowercase

Consistent with PEP8 and other functions like welch and spectrogram

* TST: Convert 2-norm tests into assert_allclose

Provides better error messages and is more consistent with other tests.

Using the tightest tolerances that pass on Windows machine.

* TST: Loosen tolerances until all CI systems pass

* ENH: Don't calculate products we don't need

If m is longer than n, this wastes time calculating values that are
immediately thrown away

* Move nfft where used

* DOC: range notation

* w isn't used, just available from class

* ENH: More accurate _Awk2 in ZoomFFT

Suggested by @llohse in
https://github.com/scipy/scipy/pull/4607#discussion_r506251925

* ENH: More accurate wk2 in CZT

Suggested by @ncgeib in
https://github.com/scipy/scipy/pull/4607#discussion_r63880528

and @mreineck in
https://github.com/scipy/scipy/pull/4607#discussion_r314938187

* TST: Tightest tolerances that will pass locally

and then will update them for the CI test platforms

* TST: Relax tolerance

* TST: Wider tolerance for ARM Test Group 1

I'm not sure why this fails.  Other systems produce identical output,
but this platform doesn't.

E   Max absolute difference: 1.80394263e-13
E   Max relative difference: 1.028472e-14

* DOC: Docstring improvements

Harmonize the docstrings of the different functions

* DOC: Remove comments about view

the line y = y[..., self._yidx] * self._wk2 creates a new array

* ENH: Add endpoint= parameter to zoomfft, and tests

* DOC: Add descriptions to scipy.fft.__doc__

Addresses https://github.com/scipy/scipy/pull/4607#discussion_r523772549

* DOC: Add See Also to all CZT/ZoomFFT docstrings

Addresses
https://github.com/scipy/scipy/pull/4607#issuecomment-727015251

* DOC: Add 'callable' to class docstrings

Addresses
https://github.com/scipy/scipy/pull/4607#issuecomment-477893359
and
https://github.com/scipy/scipy/pull/4607#issuecomment-728904715

* DOC: Add backticks around some variables

Addresses
https://github.com/scipy/scipy/pull/4607#issuecomment-727015251

* TST: Remove unused fftshift import

Addresses https://github.com/scipy/scipy/pull/4607#discussion_r523778524

* DOC: Harmonize parameter descriptions

Addresses
https://github.com/scipy/scipy/pull/4607#issuecomment-727010040

* DOC: Copy example from ZoomFFT to zoomfft

* DOC: Simplify examples to use points.real, .imag

* DOC: Add unit circles to example plots

* DOC: Add example to czt, add ref to czt, ZoomFFT

"This means that the CZT allows us to obtain spectral information only
over a band of frequencies within the range..."

* DOC: Mention Bluestein's algorithm for ZoomFFT

* DOC: Note about "chirp" in name

* DOC: Correct fs description (1/pi -> 2*pi)

To specify frequency range in radians, the sampling frequency should be
2*pi, not 1/pi.  To calculate half the unit circle, for instance:

    ZoomFFT(3, np.pi, fs=2*pi).points()

* DOC: Move note about system identification

Move to Notes section instead of after plotting, to work around
https://github.com/matplotlib/matplotlib/issues/19111

Causing the doc build errors:

WARNING: Exception occurred in plotting scipy-fft-czt-1
 from /home/circleci/repo/doc/source/generated/scipy.fft.czt.rst:
Traceback (most recent call last):
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/matplotlib/sphinxext/plot_directive.py", line 472, in run_code
    exec(code, ns)
  File "<string>", line 2
    A similar process can be used for system identification purposes,
            ^
SyntaxError: invalid syntax

* TST: Use scipy.fft imports

* Use .index() instead of checking for integer value

Co-authored-by: Eric Larson <larson.eric.d@gmail.com>

* TST: Remove run_module_suite leftovers from original code

Co-authored-by: Eric Larson <larson.eric.d@gmail.com>

* TST: Replace numpy.testing.dec with pytest.mark

* TST: Parametrize, assert_raises -> pytest.raises

Replace for loops with pytest.mark.parametrize.

Replace assert_raises with pytest.raises.

(TODO: There is probably a better way to parametrize different functions
with different numbers of arguments, parameters in different
positions, but I don't know it.)

Co-authored-by: Eric Larson <larson.eric.d@gmail.com>

* TST: Delay evaluation of classes

Co-authored-by: Eric Larson <larson.eric.d@gmail.com>

* Combine error messages, check type, not value

Instead of using operator.index(), which unnecessarily modifies the
variables and makes the error message less helpful, combine the error
messages and check the type of the integer variable, rather than the
value.

Also clarify type requirement in error message, and test for arguments
with integer value but not integer type.

Also change another error message to use f-strings.

* TST: Reorder tests to be near each other

* TST: Parametrize test_czt_math and test for w

* TST: Relax test_czt_math and choose new step size

So the functions are tested away from the unit circle, but not so far
that numerical error crops up at high m.

* TST: Workaround for type annotations

* DOC: Mention scipy.fft also uses Bluestein's algo

* Move CZT from scipy.fft.czt to scipy.signal._czt

3 mild votes for `signal`:
- https://github.com/scipy/scipy/pull/4607#issuecomment-498157401
- https://github.com/scipy/scipy/pull/4607#discussion_r574482611
- https://github.com/scipy/scipy/pull/4607#discussion_r574897594

1 vote for `fft`:
- https://github.com/scipy/scipy/pull/4607#issuecomment-739552320

Make into a private namespace like
https://github.com/scipy/scipy/pull/14962

* Change zoomfft endpoint=False default, matches fft

With this default, scipy.signal.zoomfft() == scipy.fft.fft()

https://github.com/scipy/scipy/pull/4607#issuecomment-716124250
https://github.com/scipy/scipy/pull/4607#issuecomment-896706063
https://github.com/scipy/scipy/pull/4607#issuecomment-901207245

* PEP8: Rename zoomfft to zoom_fft

https://www.python.org/dev/peps/pep-0008/#function-and-variable-names

* Set some arguments to be keyword-only

Co-authored-by: Paul Kienzle <pkienzle@users.noreply.github.com>
Co-authored-by: Eric Larson <larson.eric.d@gmail.com>