TYP: ignore missing sphinx import in mypy.ini (#21455)
Sphinx isn't required, and if it is missing we otherwise see:
```
scipy/_lib/_docscrape.py:632: error: Cannot find implementation or library stub for module named "sphinx.ext.autodoc"  [import-not-found]
```