MAINT: stats: Change a test to use <= instead of strictly less than.
Some of the tests of the fit method of the distributions compare
analytical results with numerical results for the log-likelihood using
a strict inequality.  When I run

$ python runtests.py -n -m full -t scipy.stats.tests.test_distributions

I occasionally get a failure in

    TestInvgauss.test_fit_MLE_comp_optimzer

like the one shown below.  The values being compared are

        ll_mle_analytical = 543.2306342629178
        ll_numerical_opt = 543.2306342629176

The values differ by just one ULP, and the numerical result ended up
being less than the analytical result.  More often (about a third of
the time), the two values would be the same.  Neither of these cases
should be a failure, so the test function `_assert_lessthan_loglike`
is changed to `_assert_less_or_close_loglike`.

With this change, I get no failures in over a dozen runs of the tests.

-----

This is the failure that occasionally occurred:

$ python runtests.py -n -m full -t scipy.stats.tests.test_distributions
================================================================ test session starts ================================================================
platform darwin -- Python 3.8.3, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /Users/warren/repos/git/forks/scipy, inifile: pytest.ini
plugins: hypothesis-5.20.3, forked-1.3.0, xdist-1.33.0
collected 520 items

../.. ....................................................................................................................................... [ 25%]
..........................F.................................................................................................................. [ 53%]
.........s..........................................................s....................s................................................... [ 80%]
.......................................................................................................                                       [100%]

===================================================================== FAILURES ======================================================================
__________________________ TestInvgauss.test_fit_MLE_comp_optimzer[7.506065448793064-7.935944383253818-6.9573294495867355] __________________________
/Users/warren/mc38/lib/python3.8/site-packages/scipy-1.6.0.dev0+4378d86-py3.8-macosx-10.9-x86_64.egg/scipy/stats/tests/test_distributions.py:1650: in test_fit_MLE_comp_optimzer
    _assert_le_loglike(stats.invgauss, data, func, floc=rvs_loc,
        __class__  = <class 'scipy.stats.tests.test_distributions.TestInvgauss'>
        args       = [array([  23.42460064,   12.09137691,   17.0612756 ,   14.64902961,
         62.45266594,    9.25045029,   13.93376185...
         43.63455242,  103.2703179 ,   11.03491802,   10.98263728]), ((1.0, -103.9737672516307, 167.50789530978582),)]
        data       = array([  23.42460064,   12.09137691,   17.0612756 ,   14.64902961,
         62.45266594,    9.25045029,   13.93376185,...00376,   94.51420487,   50.75174539,   20.90312291,
         43.63455242,  103.2703179 ,   11.03491802,   10.98263728])
        func       = <bound method rv_continuous._penalized_nnlf of <scipy.stats._continuous_distns.invgauss_gen object at 0x116d5a070>>
        invgauss_fit = (2, 0, 30.5608104927943)
        rvs_loc    = 7.935944383253818
        rvs_mu     = 7.506065448793064
        rvs_scale  = 6.9573294495867355
        self       = <scipy.stats.tests.test_distributions.TestInvgauss object at 0x1174906d0>
        super_fit  = <bound method rv_continuous.fit of <scipy.stats._continuous_distns.invgauss_gen object at 0x116d5a070>>
        super_fitted = (2, 0, 30.5608104927943)
/Users/warren/mc38/lib/python3.8/site-packages/scipy-1.6.0.dev0+4378d86-py3.8-macosx-10.9-x86_64.egg/scipy/stats/tests/test_distributions.py:107: in _assert_le_loglike
    assert ll_mle_analytical <= ll_numerical_opt
E   assert 543.2306342629178 <= 543.2306342629176
        data       = array([  23.42460064,   12.09137691,   17.0612756 ,   14.64902961,
         62.45266594,    9.25045029,   13.93376185,...00376,   94.51420487,   50.75174539,   20.90312291,
         43.63455242,  103.2703179 ,   11.03491802,   10.98263728])
        dist       = <scipy.stats._continuous_distns.invgauss_gen object at 0x116d5a070>
        func       = <bound method rv_continuous._penalized_nnlf of <scipy.stats._continuous_distns.invgauss_gen object at 0x116d5a070>>
        kwds       = {'floc': 7.935944383253818, 'fscale': 0.4803885080134066}
        ll_mle_analytical = 543.2306342629178
        ll_numerical_opt = 543.2306342629176
        mle_analytical = (115.73587366779743, 7.935944383253818, 0.4803885080134066)
        numerical_opt = (115.7358398437502, 7.935944383253818, 0.4803885080134066)
============================================================== short test summary info ==============================================================
FAILED ../../::TestInvgauss::test_fit_MLE_comp_optimzer[7.506065448793064-7.935944383253818-6.9573294495867355] - assert 543.2306342629178 <= 543....
===================================================== 1 failed, 516 passed, 3 skipped in 29.92s =====================================================