Removed `setup_xplt.py config` hack: config_pygist.run() is executed in setup_xplt.configuration(..) [*] and fully so only if Make.cfg does not exist (TODO: must remove Make.cfg from CVS; resolve cc issue).
Fixed
  AttributeError: 'str' object has no attribute 'append'
bug (eric's report).

Fixed os.chdir's block to ensure that original cwd is restored
in config_pygist.config_unix.

[*] distutils.command.config is not really a distutils command
in the sense that it is not registered in
distutils.command.__init__.__all__. This explains why explicit
`setup_xplt.py config` was required.