BLD: fix warning for missing dependency, and dev version number
Relevant warnings that are fixed look like:

```
fatal: bad revision '^v1.7.0'
```

```
Error: 'None' must be installed before running the build.
```