MAINT: special: get rid of _logit.c.src
Use C++ templates instead. Note the need to manually instantiate
kernels because otherwise it fails to compile with:

scipy/special/_ufuncs_cxx.cxx:4096:66: error: overloaded function with no contextual type information
 4096 |   __pyx_v_5scipy_7special_11_ufuncs_cxx__export_logit = ((void *)logit);