Fix AIX build break due to RAW Macro defined.
This PR fixes the AIX CI build break of scipy.

The build of Scipy in AIX breaks with the below error:

fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++17 -O2 -g -maix64 -fPIC -fopenmp -DNPY_NO_DEPRECATED_API=NPY_1_9_API_VERSION -MD -MQ scipy/linalg/_batched_linalg.cpython-312.so.p/src__batched_linalg_module.cc.o -MF scipy/linalg/_batched_linalg.cpython-312.so.p/src__batched_linalg_module.cc.o.d -o scipy/linalg/_batched_linalg.cpython-312.so.p/src__batched_linalg_module.cc.o -c ../scipy/linalg/src/_batched_linalg_module.cc
In file included from /usr/include/sys/termio.h:36,
                 from /opt/freeware/include/python3.12/pyport.h:441,
                 from /opt/freeware/include/python3.12/Python.h:38,
                 from ../scipy/linalg/src/_linalg_inv.hh:4,
                 from ../scipy/linalg/src/_batched_linalg_module.cc:2:
../scipy/linalg/src/_common_array_utils.hh:928:5: error: expected identifier before numeric constant
  928 |     RAW = 21,
      |     ^~~
../scipy/linalg/src/_common_array_utils.hh:928:5: error: expected '}' before numeric constant
In file included from ../scipy/linalg/src/_linalg_inv.hh:11:
../scipy/linalg/src/_common_array_utils.hh:925:1: note: to match this '{'
  925 | {
      | ^
../scipy/linalg/src/_common_array_utils.hh:928:5: error: expected unqualified-id before numeric constant
  928 |     RAW = 21,

This is because in AIX in /usr/include/sys/termio.h we include ioctl.h where AIX has a macro RAW,
which is defined as
define     RAW     0x00000020  /* no i/o processing */