MAINT: fix typo in small_dynamic_array.h (#21069)
on clang-19, this causes:
```
../scipy/_lib/_uarray/small_dynamic_array.h(145,18): error: reference to non-static member function must be called
  145 |     size_ = copy.size;
      |             ~~~~~^~~~
1 error generated.
```
I'm not sure how previous versions (much less other compilers) dealt with this,
as it seems that the `SmallDynamicArray` class has no `size` member or field at all.