TST: bump tolerance to address `test_axis_nan_policy` failures
The `normaltest` tests need 4e-15 to pass in my x86-64 linux conda-forge
environment; the `kurtosistest` tests need 6e-15. These tolerances don't
need to be this tight and my setup is unlikely to be worst-case, so
add a bit of margin on top.

Failures:
```
E   AssertionError:
E   Not equal to tolerance rtol=1e-15, atol=0
E
E   Mismatched elements: 3 / 6 (50%)
E   Max absolute difference: 7.99360578e-15
E   Max relative difference: 3.95721074e-15
E    x: array([[5.141364, 0.673337],
E          [4.039859, 2.172997],
E          [4.832018, 5.96047 ]])
E    y: array([[5.141364, 0.673337],
E          [4.039859, 2.172997],
E          [4.832018, 5.96047 ]])
        args       = (<function assert_allclose.<locals>.compare at 0x7ef45c1d6e80>, array([[5.14136359, 0.67333671],
       [4.03985923, 2...18, 5.96046984]]), array([[5.14136359, 0.67333671],
       [4.03985923, 2.17299682],
       [4.83201818, 5.96046984]]))
        func       = <function assert_array_compare at 0x7ef488122f20>
        kwds       = {'equal_nan': True, 'err_msg': '', 'header': 'Not equal to tolerance rtol=1e-15, atol=0', 'verbose': True}
        self       = <contextlib._GeneratorContextManager object at 0x7ef48811bc50>
========================================================= short test summary info ==========================================================
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--3-propagate-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--3-propagate-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--3-omit-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--3-omit-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--3-raise-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--3-raise-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--2-propagate-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--2-propagate-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--2-omit-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--2-omit-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--2-raise-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--2-raise-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--1-propagate-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--1-propagate-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--1-omit-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--1-omit-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--1-raise-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite--1-raise-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-0-propagate-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-0-propagate-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-0-omit-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-0-omit-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-0-raise-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-0-raise-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-1-propagate-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-1-propagate-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-1-omit-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-1-omit-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-1-raise-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-1-raise-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-2-propagate-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-2-propagate-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-2-omit-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-2-omit-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-2-raise-kurtosistest-args41-kwds41-1-2-False-None] - AssertionError:
FAILED scipy/stats/tests/test_axis_nan_policy.py::test_axis_nan_policy_full[all_finite-2-raise-normaltest-args42-kwds42-1-2-False-None] - AssertionError:
========================================== 36 failed, 3096 passed, 54 skipped in 66.33s (0:01:06) ==========================================
```

[skip ci]