BLD: fix a missing build dependency for `cython_special`, and add a CI check
This was technically a race condition (no one seems to have hit it yet though).
From the added CI step:

```
Run ninja -C build -t missingdeps
Missing dep: scipy/special/cython_special.cpython-310-x86_64-linux-gnu.so.p/meson-generated_cython_special.c.o uses scipy/special/_ufuncs_defs.h (generated by CUSTOM_COMMAND)
Processed 1310 nodes.
Error: There are 1 missing dependency paths.
1 targets had depfile dependencies on 1 distinct generated inputs (from 1 rules)  without a non-depfile dep path to the generator.
There might be build flakiness if any of the targets listed above are built alone, or not late enough, in a clean output directory.
```

[skip cirrus] [skip circle]