CI: pin setuptools to <60.0 for Windows and 32-bit Linux jobs on Azure
This fixes the Windows build failures with Pythran 0.11. Closes gh-15267

It also fixes the failure of the 32-bit Linux build (no separate issue
opened for that one), which looks like:

```
Adding scipy 1.9.0.dev0+unknown.unknown to easy-install.pth file

Installed /usr/lib/python3.8/site-packages/scipy-1.9.0.dev0+unknown.unknown-py3.8-linux-i686.egg
Processing dependencies for scipy==1.9.0.dev0+unknown.unknown
Searching for numpy==1.17.3
Best match: numpy 1.17.3
Adding numpy 1.17.3 to easy-install.pth file
Installing f2py script to /usr/bin
Installing f2py3 script to /usr/bin
Installing f2py3.8 script to /usr/bin

Using /root/.local/lib/python3.8/site-packages
Finished processing dependencies for scipy==1.9.0.dev0+unknown.unknown
Running from SciPy source directory.
/root/.local/lib/python3.8/site-packages/numpy/distutils/system_info.py:782: UserWarning: Specified path /root/.local/include/python3.8 is invalid.
  return self.get_paths(self.section, key)
/root/.local/lib/python3.8/site-packages/numpy/distutils/system_info.py:782: UserWarning: Specified path /usr/local/include/python3.8 is invalid.
  return self.get_paths(self.section, key)
/usr/local/lib/python3.8/dist-packages/setuptools/dist.py:493: UserWarning: Normalizing '1.9.0.dev0+Unknown.Unknown' to '1.9.0.dev0+unknown.unknown'
  warnings.warn(tmpl.format(**locals()))
/usr/local/lib/python3.8/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/setuptools/command/egg_info.py:624: SetuptoolsDeprecationWarning: Custom 'build_py' does not implement 'get_data_files_without_manifest'.
Please extend command classes from setuptools instead of distutils.
  warnings.warn(
Traceback (most recent call last):
  File "tools/openblas_support.py", line 332, in <module>
    test_version(args.check_version)
  File "tools/openblas_support.py", line 296, in test_version
    import scipy
ModuleNotFoundError: No module named 'scipy'
```

[skip github]
[skip circleci]