MAINT: special: get rid of _logit.c.src (#13931)
Ref gh-13930

Get rid of `numpy.distutils` templating in `_logit.c.src` and use C++ templates instead.

Note the need to manually instantiate templates because otherwise it fails to compile with:
```
scipy/special/_ufuncs_cxx.cxx:4096:66: error: overloaded function with no contextual type information
 4096 |   __pyx_v_5scipy_7special_11_ufuncs_cxx__export_logit = ((void *)logit);
```

Apparently `_generate_pyx.py` supports Cython fused types, so it can probably grow the template support, too. But that's for some other day certainly.